In [4]:
import numpy as np
import pandas as pd

import warnings
warnings.simplefilter('ignore', FutureWarning)

%matplotlib inline
import matplotlib.pyplot as plt

In [5]:
#Import encoded data
bankchurnersencoded = pd.read_csv('../03 Feature Engineering/bankchurnersencoded.csv')
bankchurnersencoded.head(10)

CLIENTNUM     Attrition_Flag  Customer_Age  Gender  Dependent_count  \
0  768805383  Existing Customer            45       1                3   
1  818770008  Existing Customer            49       0                5   
2  713982108  Existing Customer            51       1                3   
3  769911858  Existing Customer            40       0                4   
4  709106358  Existing Customer            40       1                3   
5  713061558  Existing Customer            44       1                2   
6  810347208  Existing Customer            51       1                4   
7  818906208  Existing Customer            32       1                0   
8  710930508  Existing Customer            37       1                3   
9  719661558  Existing Customer            48       1                2   

   Education_Level  Marital_Status  Income_Category  Card_Category  \
0                3               1                4              1   
1                5               2                2              1   
2                5               1                5              1   
3                3               3                2              1   
4                2               1                4              1   
5                5               1                3              1   
6                1               1                6              3   
7                3               3                4              2   
8                2               2                4              1   
9                5               2                5              1   

   Months_on_book  ...  Months_Inactive_12_mon  Contacts_Count_12_mon  \
0              39  ...                       1                      3   
1              44  ...                       1                      2   
2              36  ...                       1                      0   
3              34  ...                       4                      1   
4              21  ...                       1                      0   
5              36  ...                       1                      2   
6              46  ...                       1                      3   
7              27  ...                       2                      2   
8              36  ...                       2                      0   
9              36  ...                       3                      3   

   Credit_Limit  Total_Revolving_Bal  Avg_Open_To_Buy  Total_Amt_Chng_Q4_Q1  \
0       12691.0                  777          11914.0                 1.335   
1        8256.0                  864           7392.0                 1.541   
2        3418.0                    0           3418.0                 2.594   
3        3313.0                 2517            796.0                 1.405   
4        4716.0                    0           4716.0                 2.175   
5        4010.0                 1247           2763.0                 1.376   
6       34516.0                 2264          32252.0                 1.975   
7       29081.0                 1396          27685.0                 2.204   
8       22352.0                 2517          19835.0                 3.355   
9       11656.0                 1677           9979.0                 1.524   

   Total_Trans_Amt  Total_Trans_Ct  Total_Ct_Chng_Q4_Q1  Avg_Utilization_Ratio  
0             1144              42                1.625                  0.061  
1             1291              33                3.714                  0.105  
2             1887              20                2.333                  0.000  
3             1171              20                2.333                  0.760  
4              816              28                2.500                  0.000  
5             1088              24                0.846                  0.311  
6             1330              31                0.722                  0.066  
7             1538              36                0.714                  0.048  
8             

# Split data into X (features) and Y (classes)

In [6]:
# Create X data (Features)
X = bankchurnersencoded.drop(["CLIENTNUM", "Attrition_Flag"], axis=1)
print(X.shape)
X


(10127, 19)


Customer_Age  Gender  Dependent_count  Education_Level  Marital_Status  \
0                45       1                3                3               1   
1                49       0                5                5               2   
2                51       1                3                5               1   
3                40       0                4                3               3   
4                40       1                3                2               1   
...             ...     ...              ...              ...             ...   
10122            50       1                2                5               2   
10123            41       1                2                1               0   
10124            44       0                1                3               1   
10125            30       1                2                5               3   
10126            43       0                2                5               1   

       Income_Category  Card_Category  Months_on_book  \
0                    4              1              39   
1                    2              1              44   
2                    5              1              36   
3                    2              1              34   
4                    4              1              21   
...                ...            ...             ...   
10122                3              1              40   
10123                3              1              25   
10124                2              1              36   
10125                3              1              36   
10126                2              2              25   

       Total_Relationship_Count  Months_Inactive_12_mon  \
0                             5                       1   
1                             6                       1   
2                             4                       1   
3                             3                       4   
4                             5                       1   
...                         ...                     ...   
10122                         3                       2   
10123                         4                       2   
10124                         5                       3   
10125                         4                       3   
10126                         6                       2   

       Contacts_Count_12_mon  Credit_Limit  Total_Revolving_Bal  \
0                          3       12691.0                  777   
1                          2        8256.0                  864   
2                          0        3418.0                    0   
3                          1        3313.0                 2517   
4                          0        4716.0                    0   
...                      ...           ...                  ...   
10122                      3        4003.0                 1851   
10123                      3        4277.0                 2186   
10124                      4        5409.0                    0   
10125                      3        5281.0                    0   
10126                      4       10388.0                 1961   

       Avg_Open_To_Buy  Total_Amt_Chng_Q4_Q1  Total_Trans_Amt  Total_Trans_Ct  \
0              11914.0                 1.335             1144              42   
1               7392.0                 1.541             1291              33   
2               3418.0                 2.594             1887              20   
3                796.0                 1.405             1171              20   
4               4716.0                 2.175              816              28   
...                ...                   ...              ...             ...   
10122           2152.0                 0.703            15476             117   
10123           2091.0                 0.804             8764              69   
10124           5409.0                 0.819            10291              60   
10125           5281.0   

In [7]:
# Create y (classification data)
y = bankchurnersencoded["Attrition_Flag"]
print(y.shape)
y

(10127,)


0        Existing Customer
1        Existing Customer
2        Existing Customer
3        Existing Customer
4        Existing Customer
               ...        
10122    Existing Customer
10123    Attrited Customer
10124    Attrited Customer
10125    Attrited Customer
10126    Attrited Customer
Name: Attrition_Flag, Length: 10127, dtype: object

# Split data into Train and Test data

In [8]:
from sklearn.model_selection import train_test_split
from sklearn.preprocessing import LabelEncoder, MinMaxScaler
from tensorflow.keras.utils import to_categorical

In [9]:
#Define split
X_train, X_test, y_train, y_test = train_test_split(
    X, y, random_state=1)

**Resetting X_test and Y_test index**

In [10]:
X_test[:5]

Customer_Age  Gender  Dependent_count  Education_Level  Marital_Status  \
6498            43       0                2                5               1   
9013            38       0                1                4               3   
2053            39       1                2                4               1   
3211            44       1                4                5               1   
5559            38       0                2                7               1   

      Income_Category  Card_Category  Months_on_book  \
6498                2              1              36   
9013                2              1              32   
2053                4              1              31   
3211                6              1              32   
5559                2              1              28   

      Total_Relationship_Count  Months_Inactive_12_mon  Contacts_Count_12_mon  \
6498                         6                       3                      2   
9013                         2                       3                      3   
2053                         6                       3                      2   
3211                         6                       3                      4   
5559                         5                       2                      4   

      Credit_Limit  Total_Revolving_Bal  Avg_Open_To_Buy  \
6498        2570.0                 2107            463.0   
9013        2609.0                 1259           1350.0   
2053        9871.0                 1061           8810.0   
3211       34516.0                 2517          31999.0   
5559        1614.0                    0           1614.0   

      Total_Amt_Chng_Q4_Q1  Total_Trans_Amt  Total_Trans_Ct  \
6498                 0.651             4058              83   
9013                 0.871             8677              96   
2053                 0.545             1683              34   
3211                 0.765             4228              83   
5559                 0.609             2437              46   

      Total_Ct_Chng_Q4_Q1  Avg_Utilization_Ratio  
6498                0.766                  0.820  
9013                0.627                  0.483  
2053                0.478                  0.107  
3211                0.596                  0.073  
5559                0.438                  0.000

In [11]:
X_test = X_test.reset_index(drop=True)

In [12]:
X_test[:5]

Customer_Age  Gender  Dependent_count  Education_Level  Marital_Status  \
0            43       0                2                5               1   
1            38       0                1                4               3   
2            39       1                2                4               1   
3            44       1                4                5               1   
4            38       0                2                7               1   

   Income_Category  Card_Category  Months_on_book  Total_Relationship_Count  \
0                2              1              36                         6   
1                2              1              32                         2   
2                4              1              31                         6   
3                6              1              32                         6   
4                2              1              28                         5   

   Months_Inactive_12_mon  Contacts_Count_12_mon  Credit_Limit  \
0                       3                      2        2570.0   
1                       3                      3        2609.0   
2                       3                      2        9871.0   
3                       3                      4       34516.0   
4                       2                      4        1614.0   

   Total_Revolving_Bal  Avg_Open_To_Buy  Total_Amt_Chng_Q4_Q1  \
0                 2107            463.0                 0.651   
1                 1259           1350.0                 0.871   
2                 1061           8810.0                 0.545   
3                 2517          31999.0                 0.765   
4                    0           1614.0                 0.609   

   Total_Trans_Amt  Total_Trans_Ct  Total_Ct_Chng_Q4_Q1  Avg_Utilization_Ratio  
0             4058              83                0.766                  0.820  
1             8677              96                0.627                  0.483  
2             1683              34                0.478                  0.107  
3             4228              83                0.596                  0.073  
4             2437              46                0.438                  0.000

In [13]:
y_test[:5]

6498    Existing Customer
9013    Existing Customer
2053    Existing Customer
3211    Existing Customer
5559    Attrited Customer
Name: Attrition_Flag, dtype: object

In [14]:
y_test = y_test.reset_index(drop=True)
y_test[:5]

0    Existing Customer
1    Existing Customer
2    Existing Customer
3    Existing Customer
4    Attrited Customer
Name: Attrition_Flag, dtype: object

# One-hot encode Y classes

* Initial label encoding

In [15]:
# Set encoder
label_encoder = LabelEncoder()

In [16]:
# Fit Y classes to encoder
label_encoder.fit(y_train)

LabelEncoder()

In [17]:
#Transform Y-train classes - CAN ONLY DO THIS ONCE
encoded_y_train = label_encoder.transform(y_train)

In [18]:
print("Y train first ten classes")
print(y_train[:10])

Y train first ten classes
4477    Existing Customer
5191    Attrited Customer
2150    Existing Customer
1821    Existing Customer
9127    Existing Customer
1669    Existing Customer
7548    Existing Customer
7079    Existing Customer
8674    Existing Customer
4355    Existing Customer
Name: Attrition_Flag, dtype: object


In [19]:
print("Y train Encoded first ten classes")
encoded_y_train[:10]

Y train Encoded first ten classes


array([1, 0, 1, 1, 1, 1, 1, 1, 1, 1])

In [20]:
#Transform Y-test classes - CAN ONLY DO THIS ONCE
encoded_y_test = label_encoder.transform(y_test)

In [21]:
print("Y test first ten classes")
print(y_test[:10])

Y test first ten classes
0    Existing Customer
1    Existing Customer
2    Existing Customer
3    Existing Customer
4    Attrited Customer
5    Existing Customer
6    Attrited Customer
7    Existing Customer
8    Existing Customer
9    Attrited Customer
Name: Attrition_Flag, dtype: object


In [22]:
print("Y test Encoded first ten classes")
encoded_y_test[:10]

Y test Encoded first ten classes


array([1, 1, 1, 1, 0, 1, 0, 1, 1, 0])

* One-hot encoding
    * Think we may only need this if doing deep learning - other models may only require labelencoding

In [23]:
#One-hot transform Y train - CAN ONLY DO ONCE
y_train_categorical = to_categorical(encoded_y_train)

In [24]:
print("Y train first ten classes")
print(y_train[:10])

Y train first ten classes
4477    Existing Customer
5191    Attrited Customer
2150    Existing Customer
1821    Existing Customer
9127    Existing Customer
1669    Existing Customer
7548    Existing Customer
7079    Existing Customer
8674    Existing Customer
4355    Existing Customer
Name: Attrition_Flag, dtype: object


In [25]:
print("Y train One-Hot encoded first ten classes")
y_train_categorical[:10]

Y train One-Hot encoded first ten classes


array([[0., 1.],
       [1., 0.],
       [0., 1.],
       [0., 1.],
       [0., 1.],
       [0., 1.],
       [0., 1.],
       [0., 1.],
       [0., 1.],
       [0., 1.]], dtype=float32)

In [26]:
#One-hot transform Y test - CAN ONLY DO ONCE
y_test_categorical = to_categorical(encoded_y_test)

In [27]:
print("Y test first ten classes")
print(y_test[:10])

Y test first ten classes
0    Existing Customer
1    Existing Customer
2    Existing Customer
3    Existing Customer
4    Attrited Customer
5    Existing Customer
6    Attrited Customer
7    Existing Customer
8    Existing Customer
9    Attrited Customer
Name: Attrition_Flag, dtype: object


In [28]:
print("Y test One-Hot encoded first ten classes")
y_test_categorical[:10]

Y test One-Hot encoded first ten classes


array([[0., 1.],
       [0., 1.],
       [0., 1.],
       [0., 1.],
       [1., 0.],
       [0., 1.],
       [1., 0.],
       [0., 1.],
       [0., 1.],
       [1., 0.]], dtype=float32)

# Scale X data

In [29]:
#Fit X_traindata to scaler
X_scaler = MinMaxScaler().fit(X_train)

In [30]:
#Transform X-train data - CAN ONLY RUN THIS ONCE
X_train_scaled = X_scaler.transform(X_train)

In [31]:
print(X_train_scaled)

[[0.38297872 0.         0.6        ... 0.48062016 0.16155089 0.05205205]
 [0.57446809 0.         0.6        ... 0.24806202 0.08400646 0.        ]
 [0.08510638 1.         0.2        ... 0.17829457 0.19843834 0.17117117]
 ...
 [0.53191489 1.         0.4        ... 0.11627907 0.12681745 0.        ]
 [0.34042553 0.         0.6        ... 0.53488372 0.23721055 0.62162162]
 [0.61702128 1.         0.4        ... 0.13178295 0.3917609  0.14714715]]


In [32]:
#Transform X-Test data - CAN ONLY RUN THIS ONCE
X_test_scaled = X_scaler.transform(X_test)

In [33]:
X_test_scaled

array([[0.36170213, 0.        , 0.4       , ..., 0.56589147, 0.20624663,
        0.82082082],
       [0.25531915, 0.        , 0.2       , ..., 0.66666667, 0.16882068,
        0.48348348],
       [0.27659574, 1.        , 0.4       , ..., 0.18604651, 0.12870221,
        0.10710711],
       ...,
       [0.65957447, 1.        , 0.2       , ..., 0.25581395, 0.19386107,
        0.08208208],
       [0.44680851, 0.        , 0.8       , ..., 0.54263566, 0.24367259,
        0.32632633],
       [0.38297872, 1.        , 0.4       , ..., 0.72093023, 0.17097469,
        0.08408408]])

# Exporting pre-processing data to csv for future use
* At this stage this process does not work. Anyone deleveloping a ML Model will have to use the code above to generate own Pre-processed files

In [34]:
#Checking what each array looks like so we can confirm re-loading works

In [35]:
#encoded_y_train

In [36]:
#encoded_y_test

In [37]:
#y_train_categorical

In [38]:
#y_test_categorical

In [39]:
#X_train_scaled

In [40]:
#X_test_scaled

In [41]:
#Exporting each array to csv
    #https://www.geeksforgeeks.org/convert-a-numpy-array-into-a-csv-file/
    # Example: arr.tofile('data2.csv', sep = ',')
    
#encoded_y_train.tofile('encoded_y_train.csv', sep = ',')    

In [42]:
#encoded_y_test.tofile('encoded_y_test.csv', sep = ',')   

In [43]:
#y_train_categorical.tofile('y_train_categorical.csv', sep = ',')   

In [44]:
#y_test_categorical.tofile('y_test_categorical.csv', sep = ',')   

In [45]:
#X_train_scaled.tofile('X_train_scaled.csv', sep = ',')   

In [46]:
#X_test_scaled.tofile('X_test_scaled.csv', sep = ',')   