In [1]:
import numpy as np
import pandas as pd

import warnings
warnings.simplefilter('ignore', FutureWarning)

%matplotlib inline
import matplotlib.pyplot as plt

In [2]:
#Import encoded data
bankchurnersencoded = pd.read_csv('../03 Feature Engineering/bankchurnersencoded.csv')
bankchurnersencoded.head(10)

CLIENTNUM     Attrition_Flag  Customer_Age  Gender  Dependent_count  \
0  768805383  Existing Customer            45       1                3   
1  818770008  Existing Customer            49       0                5   
2  713982108  Existing Customer            51       1                3   
3  769911858  Existing Customer            40       0                4   
4  709106358  Existing Customer            40       1                3   
5  713061558  Existing Customer            44       1                2   
6  810347208  Existing Customer            51       1                4   
7  818906208  Existing Customer            32       1                0   
8  710930508  Existing Customer            37       1                3   
9  719661558  Existing Customer            48       1                2   

   Education_Level  Marital_Status  Income_Category  Card_Category  \
0                3               1                4              1   
1                5               2                2              1   
2                5               1                5              1   
3                3               3                2              1   
4                2               1                4              1   
5                5               1                3              1   
6                1               1                6              3   
7                3               3                4              2   
8                2               2                4              1   
9                5               2                5              1   

   Months_on_book  ...  Months_Inactive_12_mon  Contacts_Count_12_mon  \
0              39  ...                       1                      3   
1              44  ...                       1                      2   
2              36  ...                       1                      0   
3              34  ...                       4                      1   
4              21  ...                       1                      0   
5              36  ...                       1                      2   
6              46  ...                       1                      3   
7              27  ...                       2                      2   
8              36  ...                       2                      0   
9              36  ...                       3                      3   

   Credit_Limit  Total_Revolving_Bal  Avg_Open_To_Buy  Total_Amt_Chng_Q4_Q1  \
0       12691.0                  777          11914.0                 1.335   
1        8256.0                  864           7392.0                 1.541   
2        3418.0                    0           3418.0                 2.594   
3        3313.0                 2517            796.0                 1.405   
4        4716.0                    0           4716.0                 2.175   
5        4010.0                 1247           2763.0                 1.376   
6       34516.0                 2264          32252.0                 1.975   
7       29081.0                 1396          27685.0                 2.204   
8       22352.0                 2517          19835.0                 3.355   
9       11656.0                 1677           9979.0                 1.524   

   Total_Trans_Amt  Total_Trans_Ct  Total_Ct_Chng_Q4_Q1  Avg_Utilization_Ratio  
0             1144              42                1.625                  0.061  
1             1291              33                3.714                  0.105  
2             1887              20                2.333                  0.000  
3             1171              20                2.333                  0.760  
4              816              28                2.500                  0.000  
5             1088              24                0.846                  0.311  
6             1330              31                0.722                  0.066  
7             1538              36                0.714                  0.048  
8             

In [3]:
bankchurnersencoded.columns

Index(['CLIENTNUM', 'Attrition_Flag', 'Customer_Age', 'Gender',
       'Dependent_count', 'Education_Level', 'Marital_Status',
       'Income_Category', 'Card_Category', 'Months_on_book',
       'Total_Relationship_Count', 'Months_Inactive_12_mon',
       'Contacts_Count_12_mon', 'Credit_Limit', 'Total_Revolving_Bal',
       'Avg_Open_To_Buy', 'Total_Amt_Chng_Q4_Q1', 'Total_Trans_Amt',
       'Total_Trans_Ct', 'Total_Ct_Chng_Q4_Q1', 'Avg_Utilization_Ratio'],
      dtype='object')

# Split data into X (features) and Y (classes)

In [4]:
# Create X data (Features)
X = bankchurnersencoded.drop(["CLIENTNUM", "Attrition_Flag"], axis=1)
print(X.shape)
X


(10127, 19)


Customer_Age  Gender  Dependent_count  Education_Level  Marital_Status  \
0                45       1                3                3               1   
1                49       0                5                5               2   
2                51       1                3                5               1   
3                40       0                4                3               3   
4                40       1                3                2               1   
...             ...     ...              ...              ...             ...   
10122            50       1                2                5               2   
10123            41       1                2                1               0   
10124            44       0                1                3               1   
10125            30       1                2                5               3   
10126            43       0                2                5               1   

       Income_Category  Card_Category  Months_on_book  \
0                    4              1              39   
1                    2              1              44   
2                    5              1              36   
3                    2              1              34   
4                    4              1              21   
...                ...            ...             ...   
10122                3              1              40   
10123                3              1              25   
10124                2              1              36   
10125                3              1              36   
10126                2              2              25   

       Total_Relationship_Count  Months_Inactive_12_mon  \
0                             5                       1   
1                             6                       1   
2                             4                       1   
3                             3                       4   
4                             5                       1   
...                         ...                     ...   
10122                         3                       2   
10123                         4                       2   
10124                         5                       3   
10125                         4                       3   
10126                         6                       2   

       Contacts_Count_12_mon  Credit_Limit  Total_Revolving_Bal  \
0                          3       12691.0                  777   
1                          2        8256.0                  864   
2                          0        3418.0                    0   
3                          1        3313.0                 2517   
4                          0        4716.0                    0   
...                      ...           ...                  ...   
10122                      3        4003.0                 1851   
10123                      3        4277.0                 2186   
10124                      4        5409.0                    0   
10125                      3        5281.0                    0   
10126                      4       10388.0                 1961   

       Avg_Open_To_Buy  Total_Amt_Chng_Q4_Q1  Total_Trans_Amt  Total_Trans_Ct  \
0              11914.0                 1.335             1144              42   
1               7392.0                 1.541             1291              33   
2               3418.0                 2.594             1887              20   
3                796.0                 1.405             1171              20   
4               4716.0                 2.175              816              28   
...                ...                   ...              ...             ...   
10122           2152.0                 0.703            15476             117   
10123           2091.0                 0.804             8764              69   
10124           5409.0                 0.819            10291              60   
10125           5281.0   

In [5]:
# Create y (classification data)
y = bankchurnersencoded["Attrition_Flag"]
print(y.shape)
y

(10127,)


0        Existing Customer
1        Existing Customer
2        Existing Customer
3        Existing Customer
4        Existing Customer
               ...        
10122    Existing Customer
10123    Attrited Customer
10124    Attrited Customer
10125    Attrited Customer
10126    Attrited Customer
Name: Attrition_Flag, Length: 10127, dtype: object

# Split data into Train and Test data

In [6]:
from sklearn.model_selection import train_test_split
from sklearn.preprocessing import LabelEncoder, MinMaxScaler
from tensorflow.keras.utils import to_categorical

In [7]:
#Define split
X_train, X_test, y_train, y_test = train_test_split(
    X, y, random_state=1)

**Resetting X_test and Y_test index**

In [8]:
X_test[:5]

Customer_Age  Gender  Dependent_count  Education_Level  Marital_Status  \
6498            43       0                2                5               1   
9013            38       0                1                4               3   
2053            39       1                2                4               1   
3211            44       1                4                5               1   
5559            38       0                2                7               1   

      Income_Category  Card_Category  Months_on_book  \
6498                2              1              36   
9013                2              1              32   
2053                4              1              31   
3211                6              1              32   
5559                2              1              28   

      Total_Relationship_Count  Months_Inactive_12_mon  Contacts_Count_12_mon  \
6498                         6                       3                      2   
9013                         2                       3                      3   
2053                         6                       3                      2   
3211                         6                       3                      4   
5559                         5                       2                      4   

      Credit_Limit  Total_Revolving_Bal  Avg_Open_To_Buy  \
6498        2570.0                 2107            463.0   
9013        2609.0                 1259           1350.0   
2053        9871.0                 1061           8810.0   
3211       34516.0                 2517          31999.0   
5559        1614.0                    0           1614.0   

      Total_Amt_Chng_Q4_Q1  Total_Trans_Amt  Total_Trans_Ct  \
6498                 0.651             4058              83   
9013                 0.871             8677              96   
2053                 0.545             1683              34   
3211                 0.765             4228              83   
5559                 0.609             2437              46   

      Total_Ct_Chng_Q4_Q1  Avg_Utilization_Ratio  
6498                0.766                  0.820  
9013                0.627                  0.483  
2053                0.478                  0.107  
3211                0.596                  0.073  
5559                0.438                  0.000

In [9]:
X_test = X_test.reset_index(drop=True)

In [10]:
X_test[:5]

Customer_Age  Gender  Dependent_count  Education_Level  Marital_Status  \
0            43       0                2                5               1   
1            38       0                1                4               3   
2            39       1                2                4               1   
3            44       1                4                5               1   
4            38       0                2                7               1   

   Income_Category  Card_Category  Months_on_book  Total_Relationship_Count  \
0                2              1              36                         6   
1                2              1              32                         2   
2                4              1              31                         6   
3                6              1              32                         6   
4                2              1              28                         5   

   Months_Inactive_12_mon  Contacts_Count_12_mon  Credit_Limit  \
0                       3                      2        2570.0   
1                       3                      3        2609.0   
2                       3                      2        9871.0   
3                       3                      4       34516.0   
4                       2                      4        1614.0   

   Total_Revolving_Bal  Avg_Open_To_Buy  Total_Amt_Chng_Q4_Q1  \
0                 2107            463.0                 0.651   
1                 1259           1350.0                 0.871   
2                 1061           8810.0                 0.545   
3                 2517          31999.0                 0.765   
4                    0           1614.0                 0.609   

   Total_Trans_Amt  Total_Trans_Ct  Total_Ct_Chng_Q4_Q1  Avg_Utilization_Ratio  
0             4058              83                0.766                  0.820  
1             8677              96                0.627                  0.483  
2             1683              34                0.478                  0.107  
3             4228              83                0.596                  0.073  
4             2437              46                0.438                  0.000

In [11]:
y_test[:5]

6498    Existing Customer
9013    Existing Customer
2053    Existing Customer
3211    Existing Customer
5559    Attrited Customer
Name: Attrition_Flag, dtype: object

In [12]:
y_test = y_test.reset_index(drop=True)
y_test[:5]

0    Existing Customer
1    Existing Customer
2    Existing Customer
3    Existing Customer
4    Attrited Customer
Name: Attrition_Flag, dtype: object

# Label Encoding Y data

* Initial label encoding

In [13]:
# Set encoder
label_encoder = LabelEncoder()

In [14]:
# Fit Y classes to encoder
label_encoder.fit(y_train)

LabelEncoder()

In [15]:
#Transform Y-train classes - CAN ONLY DO THIS ONCE
encoded_y_train = label_encoder.transform(y_train)

In [16]:
print("Y train first ten classes")
print(y_train[:10])

Y train first ten classes
4477    Existing Customer
5191    Attrited Customer
2150    Existing Customer
1821    Existing Customer
9127    Existing Customer
1669    Existing Customer
7548    Existing Customer
7079    Existing Customer
8674    Existing Customer
4355    Existing Customer
Name: Attrition_Flag, dtype: object


In [17]:
print("Y train Encoded first ten classes")
encoded_y_train[:10]

Y train Encoded first ten classes


array([1, 0, 1, 1, 1, 1, 1, 1, 1, 1])

In [18]:
#Transform Y-test classes - CAN ONLY DO THIS ONCE
encoded_y_test = label_encoder.transform(y_test)

In [19]:
print("Y test first ten classes")
print(y_test[:10])

Y test first ten classes
0    Existing Customer
1    Existing Customer
2    Existing Customer
3    Existing Customer
4    Attrited Customer
5    Existing Customer
6    Attrited Customer
7    Existing Customer
8    Existing Customer
9    Attrited Customer
Name: Attrition_Flag, dtype: object


In [20]:
print("Y test Encoded first ten classes")
encoded_y_test[:10]

Y test Encoded first ten classes


array([1, 1, 1, 1, 0, 1, 0, 1, 1, 0])

# One-hot encode Y classes
    * Think we may only need this if doing deep learning - other models may only require labelencoding

In [21]:
#One-hot transform Y train - CAN ONLY DO ONCE
y_train_categorical = to_categorical(encoded_y_train)

In [22]:
print("Y train first ten classes")
print(y_train[:10])

Y train first ten classes
4477    Existing Customer
5191    Attrited Customer
2150    Existing Customer
1821    Existing Customer
9127    Existing Customer
1669    Existing Customer
7548    Existing Customer
7079    Existing Customer
8674    Existing Customer
4355    Existing Customer
Name: Attrition_Flag, dtype: object


In [23]:
print("Y train One-Hot encoded first ten classes")
y_train_categorical[:10]

Y train One-Hot encoded first ten classes


array([[0., 1.],
       [1., 0.],
       [0., 1.],
       [0., 1.],
       [0., 1.],
       [0., 1.],
       [0., 1.],
       [0., 1.],
       [0., 1.],
       [0., 1.]], dtype=float32)

In [24]:
#One-hot transform Y test - CAN ONLY DO ONCE
y_test_categorical = to_categorical(encoded_y_test)

In [25]:
print("Y test first ten classes")
print(y_test[:10])

Y test first ten classes
0    Existing Customer
1    Existing Customer
2    Existing Customer
3    Existing Customer
4    Attrited Customer
5    Existing Customer
6    Attrited Customer
7    Existing Customer
8    Existing Customer
9    Attrited Customer
Name: Attrition_Flag, dtype: object


In [26]:
print("Y test One-Hot encoded first ten classes")
y_test_categorical[:10]

Y test One-Hot encoded first ten classes


array([[0., 1.],
       [0., 1.],
       [0., 1.],
       [0., 1.],
       [1., 0.],
       [0., 1.],
       [1., 0.],
       [0., 1.],
       [0., 1.],
       [1., 0.]], dtype=float32)

# Scale X data

### Code to scale all data - not used - only need to code specific columns

In [ ]:
#Fit X_traindata to scaler - ALL COLUMNS
#X_scaler = MinMaxScaler().fit(X_train)

In [ ]:
#Transform X-train data - CAN ONLY RUN THIS ONCE
#X_train_scaled = X_scaler.transform(X_train)

In [ ]:
#print(X_train_scaled[:10])

In [ ]:
#Transform X-Test data - CAN ONLY RUN THIS ONCE
#X_test_scaled = X_scaler.transform(X_test)

In [ ]:
#X_test_scaled

### Code to scale specific columns (features)
https://www.codegrepper.com/code-examples/python/can+i+scale+certain+columns+in+my+pandas+dataframe%3F

In [27]:
#List columns that need scaling
col_names = ['Months_on_book', 'Total_Relationship_Count', 'Months_Inactive_12_mon',
       'Contacts_Count_12_mon', 'Credit_Limit', 'Total_Revolving_Bal',
       'Avg_Open_To_Buy', 'Total_Amt_Chng_Q4_Q1', 'Total_Trans_Amt',
       'Total_Trans_Ct', 'Total_Ct_Chng_Q4_Q1', 'Avg_Utilization_Ratio']
col_names

['Months_on_book',
 'Total_Relationship_Count',
 'Months_Inactive_12_mon',
 'Contacts_Count_12_mon',
 'Credit_Limit',
 'Total_Revolving_Bal',
 'Avg_Open_To_Buy',
 'Total_Amt_Chng_Q4_Q1',
 'Total_Trans_Amt',
 'Total_Trans_Ct',
 'Total_Ct_Chng_Q4_Q1',
 'Avg_Utilization_Ratio']

**Set up X-train data**

In [28]:
#Copy the dataframe
X_train_scaled = X_train.copy()

In [29]:
#Create dataframe of just the columns to be scaled
X_train_features = X_train_scaled[col_names]
X_train_features.head()

Months_on_book  Total_Relationship_Count  Months_Inactive_12_mon  \
4477              31                         4                       2   
5191              36                         4                       3   
2150              17                         5                       1   
1821              36                         6                       2   
9127              46                         2                       3   

      Contacts_Count_12_mon  Credit_Limit  Total_Revolving_Bal  \
4477                      3       18056.0                  940   
5191                      6        7939.0                    0   
2150                      2        7173.0                 1227   
1821                      4        3586.0                 1414   
9127                      2       34516.0                    0   

      Avg_Open_To_Buy  Total_Amt_Chng_Q4_Q1  Total_Trans_Amt  Total_Trans_Ct  \
4477          17116.0                 0.629             4473              72   
5191           7939.0                 0.551             2269              42   
2150           5946.0                 0.646             1793              33   
1821           2172.0                 0.745             2780              57   
9127          34516.0                 0.887             8416              93   

      Total_Ct_Chng_Q4_Q1  Avg_Utilization_Ratio  
4477                0.600                  0.052  
5191                0.312                  0.000  
2150                0.737                  0.171  
1821                0.727                  0.394  
9127                0.632                  0.000

In [30]:
X_train_features.values

array([[3.100e+01, 4.000e+00, 2.000e+00, ..., 7.200e+01, 6.000e-01,
        5.200e-02],
       [3.600e+01, 4.000e+00, 3.000e+00, ..., 4.200e+01, 3.120e-01,
        0.000e+00],
       [1.700e+01, 5.000e+00, 1.000e+00, ..., 3.300e+01, 7.370e-01,
        1.710e-01],
       ...,
       [3.900e+01, 3.000e+00, 3.000e+00, ..., 2.500e+01, 4.710e-01,
        0.000e+00],
       [3.500e+01, 3.000e+00, 2.000e+00, ..., 7.900e+01, 8.810e-01,
        6.210e-01],
       [4.800e+01, 4.000e+00, 3.000e+00, ..., 2.700e+01, 1.455e+00,
        1.470e-01]])

In [31]:
X_train_features

Months_on_book  Total_Relationship_Count  Months_Inactive_12_mon  \
4477              31                         4                       2   
5191              36                         4                       3   
2150              17                         5                       1   
1821              36                         6                       2   
9127              46                         2                       3   
...              ...                       ...                     ...   
2895              38                         3                       1   
7813              31                         2                       5   
905               39                         3                       3   
5192              35                         3                       2   
235               48                         4                       3   

      Contacts_Count_12_mon  Credit_Limit  Total_Revolving_Bal  \
4477                      3       18056.0                  940   
5191                      6        7939.0                    0   
2150                      2        7173.0                 1227   
1821                      4        3586.0                 1414   
9127                      2       34516.0                    0   
...                     ...           ...                  ...   
2895                      4       11373.0                 1319   
7813                      2        2153.0                 1392   
905                       1       16868.0                    0   
5192                      2        2555.0                 1587   
235                       2        8863.0                 1301   

      Avg_Open_To_Buy  Total_Amt_Chng_Q4_Q1  Total_Trans_Amt  Total_Trans_Ct  \
4477          17116.0                 0.629             4473              72   
5191           7939.0                 0.551             2269              42   
2150           5946.0                 0.646             1793              33   
1821           2172.0                 0.745             2780              57   
9127          34516.0                 0.887             8416              93   
...               ...                   ...              ...             ...   
2895          10054.0                 0.693             1976              35   
7813            761.0                 0.787             4268              85   
905           16868.0                 0.938              940              25   
5192            968.0                 1.088             4193              79   
235            7562.0                 1.207             1512              27   

      Total_Ct_Chng_Q4_Q1  Avg_Utilization_Ratio  
4477                0.600                  0.052  
5191                0.312                  0.000  
2150                0.737                  0.171  
1821                0.727                  0.394  
9127                0.632                  0.000  
...                   ...                    ...  
2895                0.750                  0.116  
7813                0.667                  0.647  
905                 0.471                  0.000  
5192                0.881                  0.621  
235                 1.455                  0.147  

[7595 rows x 12 columns]

In [32]:
#import scaler
#Code to load the scaler when required
from pickle import load

In [33]:
X_scaler = load(open('X_scaler.pkl', 'rb'))

**Create scaling model**

In [34]:
#Create scaler model using values array of the df
X_scaler = MinMaxScaler().fit(X_train_features.values)
X_scaler

MinMaxScaler()

In [35]:
#Transform the data
X_train_features = X_scaler.transform(X_train_features.values)
X_train_features

array([[0.41860465, 0.6       , 0.33333333, ..., 0.48062016, 0.16155089,
        0.05205205],
       [0.53488372, 0.6       , 0.5       , ..., 0.24806202, 0.08400646,
        0.        ],
       [0.09302326, 0.8       , 0.16666667, ..., 0.17829457, 0.19843834,
        0.17117117],
       ...,
       [0.60465116, 0.4       , 0.5       , ..., 0.11627907, 0.12681745,
        0.        ],
       [0.51162791, 0.4       , 0.33333333, ..., 0.53488372, 0.23721055,
        0.62162162],
       [0.81395349, 0.6       , 0.5       , ..., 0.13178295, 0.3917609 ,
        0.14714715]])

**Update data frame**

In [36]:
#Updated originally copied df with new scaled features
X_train_scaled[col_names] = X_train_features

In [37]:
X_train_scaled.head()

Customer_Age  Gender  Dependent_count  Education_Level  Marital_Status  \
4477            44       0                3                2               2   
5191            53       0                3                3               0   
2150            30       1                1                6               1   
1821            37       0                2                3               2   
9127            56       0                3                2               2   

      Income_Category  Card_Category  Months_on_book  \
4477                1              1        0.418605   
5191                1              1        0.534884   
2150                2              1        0.093023   
1821                2              1        0.534884   
9127                1              4        0.767442   

      Total_Relationship_Count  Months_Inactive_12_mon  Contacts_Count_12_mon  \
4477                       0.6                0.333333               0.500000   
5191                       0.6                0.500000               1.000000   
2150                       0.8                0.166667               0.333333   
1821                       1.0                0.333333               0.666667   
9127                       0.2                0.500000               0.333333   

      Credit_Limit  Total_Revolving_Bal  Avg_Open_To_Buy  \
4477      0.502384             0.373460         0.495842   
5191      0.196528             0.000000         0.229942   
2150      0.173371             0.487485         0.172196   
1821      0.064929             0.561780         0.062846   
9127      1.000000             0.000000         1.000000   

      Total_Amt_Chng_Q4_Q1  Total_Trans_Amt  Total_Trans_Ct  \
4477              0.185163         0.226651        0.480620   
5191              0.162202         0.100601        0.248062   
2150              0.190168         0.073377        0.178295   
1821              0.219311         0.129826        0.364341   
9127              0.261113         0.452159        0.643411   

      Total_Ct_Chng_Q4_Q1  Avg_Utilization_Ratio  
4477             0.161551               0.052052  
5191             0.084006               0.000000  
2150             0.198438               0.171171  
1821             0.195746               0.394394  
9127             0.170167               0.000000

**Pass X-test data through scaling model**

In [38]:
#Copy the dataframe
X_test_scaled = X_test.copy()

In [39]:
#Create dataframe of just the columns to be scaled
X_test_features = X_test_scaled[col_names]
X_test_features.head()

Months_on_book  Total_Relationship_Count  Months_Inactive_12_mon  \
0              36                         6                       3   
1              32                         2                       3   
2              31                         6                       3   
3              32                         6                       3   
4              28                         5                       2   

   Contacts_Count_12_mon  Credit_Limit  Total_Revolving_Bal  Avg_Open_To_Buy  \
0                      2        2570.0                 2107            463.0   
1                      3        2609.0                 1259           1350.0   
2                      2        9871.0                 1061           8810.0   
3                      4       34516.0                 2517          31999.0   
4                      4        1614.0                    0           1614.0   

   Total_Amt_Chng_Q4_Q1  Total_Trans_Amt  Total_Trans_Ct  Total_Ct_Chng_Q4_Q1  \
0                 0.651             4058              83                0.766   
1                 0.871             8677              96                0.627   
2                 0.545             1683              34                0.478   
3                 0.765             4228              83                0.596   
4                 0.609             2437              46                0.438   

   Avg_Utilization_Ratio  
0                  0.820  
1                  0.483  
2                  0.107  
3                  0.073  
4                  0.000

In [40]:
#Transform the data
X_test_features = X_scaler.transform(X_test_features.values)
X_test_features

array([[0.53488372, 1.        , 0.5       , ..., 0.56589147, 0.20624663,
        0.82082082],
       [0.44186047, 0.2       , 0.5       , ..., 0.66666667, 0.16882068,
        0.48348348],
       [0.41860465, 1.        , 0.5       , ..., 0.18604651, 0.12870221,
        0.10710711],
       ...,
       [0.53488372, 1.        , 0.33333333, ..., 0.25581395, 0.19386107,
        0.08208208],
       [0.53488372, 0.4       , 0.33333333, ..., 0.54263566, 0.24367259,
        0.32632633],
       [0.55813953, 0.2       , 0.5       , ..., 0.72093023, 0.17097469,
        0.08408408]])

In [41]:
#Updated originally copied df with new scaled features
X_test_scaled[col_names] = X_test_features

In [42]:
X_test_scaled.head()

Customer_Age  Gender  Dependent_count  Education_Level  Marital_Status  \
0            43       0                2                5               1   
1            38       0                1                4               3   
2            39       1                2                4               1   
3            44       1                4                5               1   
4            38       0                2                7               1   

   Income_Category  Card_Category  Months_on_book  Total_Relationship_Count  \
0                2              1        0.534884                       1.0   
1                2              1        0.441860                       0.2   
2                4              1        0.418605                       1.0   
3                6              1        0.441860                       1.0   
4                2              1        0.348837                       0.8   

   Months_Inactive_12_mon  Contacts_Count_12_mon  Credit_Limit  \
0                0.500000               0.333333      0.034213   
1                0.500000               0.500000      0.035392   
2                0.500000               0.333333      0.254936   
3                0.500000               0.666667      1.000000   
4                0.333333               0.666667      0.005312   

   Total_Revolving_Bal  Avg_Open_To_Buy  Total_Amt_Chng_Q4_Q1  \
0             0.837108         0.013328              0.191640   
1             0.500199         0.039029              0.256403   
2             0.421534         0.255179              0.160436   
3             1.000000         0.927071              0.225199   
4             0.000000         0.046678              0.179276   

   Total_Trans_Amt  Total_Trans_Ct  Total_Ct_Chng_Q4_Q1  Avg_Utilization_Ratio  
0         0.202917        0.565891             0.206247               0.820821  
1         0.467086        0.666667             0.168821               0.483483  
2         0.067086        0.186047             0.128702               0.107107  
3         0.212639        0.565891             0.160474               0.073073  
4         0.110209        0.279070             0.117932               0.000000

# Exporting scaler for use with machine learning

In [43]:
from pickle import dump

In [44]:
# save the scaler
dump(X_scaler, open('X_scaler.pkl', 'wb'))

In [45]:
#Code to load the scaler when required
from pickle import load

In [46]:
X_scaler = load(open('X_scaler.pkl', 'rb'))

# Exporting pre-processing data to csv for future use
* At this stage this process does not work. Anyone deleveloping a ML Model will have to use the code above to generate own Pre-processed files

In [ ]:
#Checking what each array looks like so we can confirm re-loading works

In [ ]:
#encoded_y_train

In [ ]:
#encoded_y_test

In [ ]:
#y_train_categorical

In [ ]:
#y_test_categorical

In [ ]:
#X_train_scaled

In [ ]:
#X_test_scaled

In [ ]:
#Exporting each array to csv
    #https://www.geeksforgeeks.org/convert-a-numpy-array-into-a-csv-file/
    # Example: arr.tofile('data2.csv', sep = ',')
    
#encoded_y_train.tofile('encoded_y_train.csv', sep = ',')    

In [ ]:
#encoded_y_test.tofile('encoded_y_test.csv', sep = ',')   

In [ ]:
#y_train_categorical.tofile('y_train_categorical.csv', sep = ',')   

In [ ]:
#y_test_categorical.tofile('y_test_categorical.csv', sep = ',')   

In [ ]:
#X_train_scaled.tofile('X_train_scaled.csv', sep = ',')   

In [ ]:
#X_test_scaled.tofile('X_test_scaled.csv', sep = ',')   