In [1]:
import numpy as np
import pandas as pd

import warnings
warnings.simplefilter('ignore', FutureWarning)

%matplotlib inline
import matplotlib.pyplot as plt

In [2]:
# Importing CSV and converting to numpy array
    #https://intellipaat.com/community/9398/how-do-i-read-csv-data-into-a-record-array-in-numpy#:~:text=To%20read%20CSV%20data%20into,the%20delimiter%20to%20a%20comma.&text=You%20can%20also%20use%20the,a%20record%20array%20in%20NumPy.&text=df.
from numpy import genfromtxt

In [3]:
encoded_y_train = genfromtxt('encoded_y_train.csv', delimiter=',')

In [8]:
encoded_y_test = genfromtxt('encoded_y_test.csv', delimiter=',')

In [9]:
y_test_categorical = genfromtxt('y_test_categorical.csv', delimiter=',')

In [10]:
y_train_categorical = genfromtxt('y_train_categorical.csv', delimiter=',')

In [11]:
X_train_scaled = genfromtxt('X_train_scaled.csv', delimiter=',')

In [12]:
X_test_scaled = genfromtxt('X_test_scaled.csv', delimiter=',')

In [19]:
encoded_y_train[:5]

array([1., 0., 1., 1., 1.])

In [20]:
encoded_y_test[:5]

array([1., 1., 1., 1., 0.])

In [21]:
y_train_categorical[:5]

array([0., 1., 1., 0., 0.])

In [22]:
y_test_categorical[:5]

array([0., 1., 0., 1., 0.])

In [25]:
X_train_scaled

array([0.38297872, 0.        , 0.6       , ..., 0.13178295, 0.3917609 ,
       0.14714715])

In [24]:
X_test_scaled[:5]

array([0.36170213, 0.        , 0.4       , 0.66666667, 0.33333333])