In [118]:
import numpy as np
import pandas as pd

import warnings
warnings.simplefilter('ignore', FutureWarning)

%matplotlib inline
import matplotlib.pyplot as plt

import pickle

In [119]:
#https://www.thepythoncode.com/article/extracting-and-submitting-web-page-forms-in-python
# # Seaborn visualization library
# import seaborn as sns
# # Create the default pairplot
# sns.pairplot(df)

# Pre-processing code from template - START
Project3Git/04 Pre-processing Template/01 Pre-processing- X-Y split - Y One-Hot Encoding - Train-Test Split - Scaling X Training Data.ipynb

In [120]:
#Import encoded data
bankchurnersencoded = pd.read_csv('../03 Feature Engineering/bankchurnersencoded.csv')
bankchurnersencoded.head(10)

CLIENTNUM     Attrition_Flag  Customer_Age  Gender  Dependent_count  \
0  768805383  Existing Customer            45       1                3   
1  818770008  Existing Customer            49       0                5   
2  713982108  Existing Customer            51       1                3   
3  769911858  Existing Customer            40       0                4   
4  709106358  Existing Customer            40       1                3   
5  713061558  Existing Customer            44       1                2   
6  810347208  Existing Customer            51       1                4   
7  818906208  Existing Customer            32       1                0   
8  710930508  Existing Customer            37       1                3   
9  719661558  Existing Customer            48       1                2   

   Education_Level  Marital_Status  Income_Category  Card_Category  \
0                3               1                4              1   
1                5               2                2              1   
2                5               1                5              1   
3                3               3                2              1   
4                2               1                4              1   
5                5               1                3              1   
6                1               1                6              3   
7                3               3                4              2   
8                2               2                4              1   
9                5               2                5              1   

   Months_on_book  ...  Months_Inactive_12_mon  Contacts_Count_12_mon  \
0              39  ...                       1                      3   
1              44  ...                       1                      2   
2              36  ...                       1                      0   
3              34  ...                       4                      1   
4              21  ...                       1                      0   
5              36  ...                       1                      2   
6              46  ...                       1                      3   
7              27  ...                       2                      2   
8              36  ...                       2                      0   
9              36  ...                       3                      3   

   Credit_Limit  Total_Revolving_Bal  Avg_Open_To_Buy  Total_Amt_Chng_Q4_Q1  \
0       12691.0                  777          11914.0                 1.335   
1        8256.0                  864           7392.0                 1.541   
2        3418.0                    0           3418.0                 2.594   
3        3313.0                 2517            796.0                 1.405   
4        4716.0                    0           4716.0                 2.175   
5        4010.0                 1247           2763.0                 1.376   
6       34516.0                 2264          32252.0                 1.975   
7       29081.0                 1396          27685.0                 2.204   
8       22352.0                 2517          19835.0                 3.355   
9       11656.0                 1677           9979.0                 1.524   

   Total_Trans_Amt  Total_Trans_Ct  Total_Ct_Chng_Q4_Q1  Avg_Utilization_Ratio  
0             1144              42                1.625                  0.061  
1             1291              33                3.714                  0.105  
2             1887              20                2.333                  0.000  
3             1171              20                2.333                  0.760  
4              816              28                2.500                  0.000  
5             1088              24                0.846                  0.311  
6             1330              31                0.722                  0.066  
7             1538              36                0.714                  0.048  
8             

# Split data into X (features) and Y (classes)

In [121]:
# Create X data (Features)
X = bankchurnersencoded.drop(["CLIENTNUM", "Attrition_Flag"], axis=1)
print(X.shape)

(10127, 19)


In [122]:
# Create y (classification data)
y = bankchurnersencoded["Attrition_Flag"]
print(y.shape)

(10127,)


# Split data into Train and Test data

In [123]:
from sklearn.model_selection import train_test_split
from sklearn.preprocessing import LabelEncoder, MinMaxScaler
from tensorflow.keras.utils import to_categorical

In [124]:
#Define split
X_train, X_test, y_train, y_test = train_test_split(
    X, y, random_state=1)

**Resetting X_test and Y_test index**

In [125]:
X_test = X_test.reset_index(drop=True)
X_test[:5]

Customer_Age  Gender  Dependent_count  Education_Level  Marital_Status  \
0            43       0                2                5               1   
1            38       0                1                4               3   
2            39       1                2                4               1   
3            44       1                4                5               1   
4            38       0                2                7               1   

   Income_Category  Card_Category  Months_on_book  Total_Relationship_Count  \
0                2              1              36                         6   
1                2              1              32                         2   
2                4              1              31                         6   
3                6              1              32                         6   
4                2              1              28                         5   

   Months_Inactive_12_mon  Contacts_Count_12_mon  Credit_Limit  \
0                       3                      2        2570.0   
1                       3                      3        2609.0   
2                       3                      2        9871.0   
3                       3                      4       34516.0   
4                       2                      4        1614.0   

   Total_Revolving_Bal  Avg_Open_To_Buy  Total_Amt_Chng_Q4_Q1  \
0                 2107            463.0                 0.651   
1                 1259           1350.0                 0.871   
2                 1061           8810.0                 0.545   
3                 2517          31999.0                 0.765   
4                    0           1614.0                 0.609   

   Total_Trans_Amt  Total_Trans_Ct  Total_Ct_Chng_Q4_Q1  Avg_Utilization_Ratio  
0             4058              83                0.766                  0.820  
1             8677              96                0.627                  0.483  
2             1683              34                0.478                  0.107  
3             4228              83                0.596                  0.073  
4             2437              46                0.438                  0.000

In [126]:
y_test = y_test.reset_index(drop=True)
y_test[:5]

0    Existing Customer
1    Existing Customer
2    Existing Customer
3    Existing Customer
4    Attrited Customer
Name: Attrition_Flag, dtype: object

# One-hot encode Y classes

* Initial label encoding

In [127]:
# Set encoder
label_encoder = LabelEncoder()

In [128]:
# Fit Y classes to encoder
label_encoder.fit(y_train)

LabelEncoder()

In [129]:
#Transform Y-train classes - CAN ONLY DO THIS ONCE
encoded_y_train = label_encoder.transform(y_train)

In [130]:
print("Y train first ten classes")
print(y_train[:10])

Y train first ten classes
4477    Existing Customer
5191    Attrited Customer
2150    Existing Customer
1821    Existing Customer
9127    Existing Customer
1669    Existing Customer
7548    Existing Customer
7079    Existing Customer
8674    Existing Customer
4355    Existing Customer
Name: Attrition_Flag, dtype: object


In [131]:
print("Y train Encoded first ten classes")
print(encoded_y_train[:10])

Y train Encoded first ten classes
[1 0 1 1 1 1 1 1 1 1]


In [132]:
#Transform Y-test classes - CAN ONLY DO THIS ONCE
encoded_y_test = label_encoder.transform(y_test)

In [133]:
print("Y test first ten classes")
print(y_test[:10])

Y test first ten classes
0    Existing Customer
1    Existing Customer
2    Existing Customer
3    Existing Customer
4    Attrited Customer
5    Existing Customer
6    Attrited Customer
7    Existing Customer
8    Existing Customer
9    Attrited Customer
Name: Attrition_Flag, dtype: object


In [134]:
print("Y test Encoded first ten classes")
print(encoded_y_test[:10])

Y test Encoded first ten classes
[1 1 1 1 0 1 0 1 1 0]


* One-hot encoding
    * Think we may only need this if doing deep learning - other models may only require labelencoding

In [135]:
#One-hot transform Y train - CAN ONLY DO ONCE
y_train_categorical = to_categorical(encoded_y_train)

In [136]:
print("Y train first ten classes")
print(y_train[:10])

Y train first ten classes
4477    Existing Customer
5191    Attrited Customer
2150    Existing Customer
1821    Existing Customer
9127    Existing Customer
1669    Existing Customer
7548    Existing Customer
7079    Existing Customer
8674    Existing Customer
4355    Existing Customer
Name: Attrition_Flag, dtype: object


In [137]:
print("Y train One-Hot encoded first ten classes")
print(y_train_categorical[:10])

Y train One-Hot encoded first ten classes
[[0. 1.]
 [1. 0.]
 [0. 1.]
 [0. 1.]
 [0. 1.]
 [0. 1.]
 [0. 1.]
 [0. 1.]
 [0. 1.]
 [0. 1.]]


In [138]:
#One-hot transform Y test - CAN ONLY DO ONCE
y_test_categorical = to_categorical(encoded_y_test)

In [139]:
print("Y test first ten classes")
print(y_test[:10])

Y test first ten classes
0    Existing Customer
1    Existing Customer
2    Existing Customer
3    Existing Customer
4    Attrited Customer
5    Existing Customer
6    Attrited Customer
7    Existing Customer
8    Existing Customer
9    Attrited Customer
Name: Attrition_Flag, dtype: object


In [140]:
print("Y test One-Hot encoded first ten classes")
print(y_test_categorical[:10])

Y test One-Hot encoded first ten classes
[[0. 1.]
 [0. 1.]
 [0. 1.]
 [0. 1.]
 [1. 0.]
 [0. 1.]
 [1. 0.]
 [0. 1.]
 [0. 1.]
 [1. 0.]]


# Scale X data

### Code to scale specific columns (features)

In [141]:
#Import Scaler
from pickle import load
X_scaler = load(open('../04 Pre-processing Template/X_scaler.pkl', 'rb'))

In [ ]:
#List columns that need scaling
col_names = ['Months_on_book', 'Total_Relationship_Count', 'Months_Inactive_12_mon',
       'Contacts_Count_12_mon', 'Credit_Limit', 'Total_Revolving_Bal',
       'Avg_Open_To_Buy', 'Total_Amt_Chng_Q4_Q1', 'Total_Trans_Amt',
       'Total_Trans_Ct', 'Total_Ct_Chng_Q4_Q1', 'Avg_Utilization_Ratio']
col_names

**Pass X_train data through scaling model**

In [ ]:
#Copy the dataframe
X_train_scaled = X_train.copy()

In [ ]:
#Create dataframe of just the columns to be scaled
X_train_features = X_train_scaled[col_names]
X_train_features.head()

In [ ]:
#Transform the data
X_train_features = X_scaler.transform(X_train_features.values)
X_train_features

**Update data frame**

In [ ]:
#Updated originally copied df with new scaled features
X_train_scaled[col_names] = X_train_features

In [ ]:
# X_train_scaled.head()

**Pass X-test data through scaling model**

In [ ]:
#Copy the dataframe
X_test_scaled = X_test.copy()

In [ ]:
#Create dataframe of just the columns to be scaled
X_test_features = X_test_scaled[col_names]
X_test_features.head()

In [ ]:
#Transform the data
X_test_features = X_scaler.transform(X_test_features.values)
X_test_features

In [ ]:
#Updated originally copied df with new scaled features
X_test_scaled[col_names] = X_test_features

In [ ]:
X_test_scaled.head()

Old code for scaling entire data - which is not required

In [ ]:
#Scaling specific columns test
# X_scaler = MinMaxScaler()

In [ ]:
#Fit X_traindata to scaler
# X_scaler = MinMaxScaler().fit(X_train)

In [ ]:
#Transform X-train data - CAN ONLY RUN THIS ONCE
# X_train_scaled = X_scaler.transform(X_train)

In [ ]:
#Transform X-Test data - CAN ONLY RUN THIS ONCE
# X_test_scaled = X_scaler.transform(X_test)

In [ ]:
# X_test_scaled[:10]

# Pre-processing code from template - STOP

# Machine Learning Model - Decision Tree

In [ ]:
# Uncomment pip install if sklearn not up to date 
# Update sklearn to prevent version mismatches
#!pip install sklearn --upgrade

In [ ]:
# Uncomment if joblib not installed
# install joblib. This will be used to save your model. 
# Restart your kernel after installing 
#!pip install joblib

In [ ]:
import os

In [ ]:
from sklearn import tree

In [ ]:
#define the model
classifier = tree.DecisionTreeClassifier()
classifier

In [ ]:
#Fit the model
classifier = classifier.fit(X_train_scaled, y_train_categorical)

In [ ]:
#Score the model
print(f"Training Data Score: {classifier.score(X_train_scaled, y_train_categorical)}")
print(f"Testing Data Score: {classifier.score(X_test_scaled, y_test_categorical)}")

## Prediction

In [ ]:
predictions_tree = classifier.predict(X_test_scaled)

In [ ]:
#https://stackoverflow.com/questions/47380663/numpy-reverse-keras-to-categorical
predictions_tree_decoded = np.argmax(predictions_tree, axis=1)
predictions_tree_decoded

In [ ]:
#https://scikit-learn.org/stable/modules/generated/sklearn.preprocessing.LabelEncoder.html
predictions_tree_labels = label_encoder.inverse_transform(predictions_tree_decoded)

In [ ]:
predictions_tree_labels

In [ ]:
y_test

In [ ]:
y_test_string = y_test.reset_index(drop=True)

In [ ]:
#print("Tree Predicted Labels:")
# for i in range(0,50):
#     print(f"Tree Predicted Output:{predictions_tree[i]} {predictions_tree_labels[i]} - Actual classification: {y_test_string[i]}")
# print("-" * 20)

## Create comparison data frame

In [ ]:
#print("Tree Predicted Labels:")
# for i in range(0,50):
#     print(f"Tree Predicted Output:{predictions_tree[i]} {predictions_tree_labels[i]} - Actual classification: {y_test_string[i]}")
# print("-" * 20)

In [ ]:
#Dataframe
comparison_tree = pd.DataFrame({'Prediction Class': predictions_tree_decoded,
                                'Prediction Label':predictions_tree_labels,
                                'Actual Label':y_test})
comparison_tree[:50]

In [ ]:
#Find all Predicted Attrited Customers
#onlybilly = df.loc[df[“first name”] == “Billy”, :]
attrited_only = comparison_tree.loc[comparison_tree["Prediction Label"] == "Attrited Customer", :]
print(f"In the Test data there is {len(attrited_only)} attrited customers out of {len(comparison_tree)} records.")
attrited_only[:10]

In [ ]:
#From predicted Attrited customers, find all actual labels equal to Existing Customer 
incorrect_attrited = attrited_only.loc[attrited_only["Actual Label"] == "Existing Customer", :]
print(f"There are {len(incorrect_attrited)} incorrectly predicted attrited customers out of {len(attrited_only)} predicted attrities")
Percent_correct = str(round(((len(attrited_only)-len(incorrect_attrited))/len(attrited_only))*100, 2))
print(f"This is an actual accuracy of {Percent_correct}%.")
incorrect_attrited
      

# Machine Learning Model - Random Forest Model

In [ ]:
from sklearn.ensemble import RandomForestClassifier

In [ ]:
#Define model
randomforestmodel = RandomForestClassifier(n_estimators=200)

In [ ]:
#Fit the model
randomforest = randomforestmodel.fit(X_train_scaled, y_train_categorical)

In [ ]:
# Score the model
print(f"Training Data Score: {randomforest.score(X_train_scaled, y_train_categorical)}")
print(f"Testing Data Score: {randomforest.score(X_test_scaled, y_test_categorical)}")

## Prediction

In [ ]:
predictions_forest = randomforest.predict(X_test_scaled)

In [ ]:
predictions_forest_decoded = np.argmax(predictions_forest, axis=1)
predictions_forest_decoded

In [ ]:
predictions_forest_labels = label_encoder.inverse_transform(predictions_forest_decoded)
predictions_forest_labels[:10]

## Create comparison data frame

In [ ]:
comparison_forest = pd.DataFrame({'Prediction Class': predictions_forest_decoded,
                                'Prediction Label':predictions_forest_labels,
                                'Actual Label':y_test})
comparison_forest[:50]

In [ ]:
#Find all Predicted Attrited Customers
attrited_only_forest = comparison_forest.loc[comparison_forest["Prediction Label"] == "Attrited Customer", :]
print(f"In the Test data there is {len(attrited_only_forest)} attrited customers out of {len(comparison_forest)} records.")
attrited_only_forest[:10]

In [ ]:
#From predicted Attrited customers, find all actual labels equal to Existing Customer 
incorrect_attrited_forest = attrited_only_forest.loc[attrited_only_forest["Actual Label"] == "Existing Customer", :]
print(f"There are {len(incorrect_attrited_forest)} incorrectly predicted attrited customers out of {len(attrited_only_forest)} predicted attrities")
Percent_correct_forest = str(round(((len(attrited_only_forest)-len(incorrect_attrited_forest))/len(attrited_only_forest))*100, 2))
print(f"This is an actual accuracy of {Percent_correct_forest}%.")
incorrect_attrited_forest

# Save the model - Random Forest
https://mljar.com/blog/save-load-random-forest/

In [ ]:
# save your model by updating "your_name" with your name
# and "your_model" with your model variable
# be sure to turn this in to BCS
# if joblib fails to import, try running the command to install in terminal/git-bash
import joblib
filename = 'randomforest_model_trained.sav'
joblib.dump(randomforest, filename)

In [ ]:
#Save using pickle as joblib nbot importing in app.py
pickle.dump(randomforest, open(filename, 'wb'))