In [55]:
import numpy as np
import pandas as pd
import os
import pickle
#https://www.journaldev.com/15638/python-pickle-example
#https://machinelearningmastery.com/save-load-machine-learning-models-python-scikit-learn/

In [56]:
df_column_names = ['Customer_Age', 'Gender',
       'Dependent_count', 'Education_Level', 'Marital_Status',
       'Income_Category', 'Card_Category', 'Months_on_book',
       'Total_Relationship_Count', 'Months_Inactive_12_mon',
       'Contacts_Count_12_mon', 'Credit_Limit', 'Total_Revolving_Bal',
       'Avg_Open_To_Buy', 'Total_Amt_Chng_Q4_Q1', 'Total_Trans_Amt',
       'Total_Trans_Ct', 'Total_Ct_Chng_Q4_Q1', 'Avg_Utilization_Ratio']
df_column_names

['Customer_Age',
 'Gender',
 'Dependent_count',
 'Education_Level',
 'Marital_Status',
 'Income_Category',
 'Card_Category',
 'Months_on_book',
 'Total_Relationship_Count',
 'Months_Inactive_12_mon',
 'Contacts_Count_12_mon',
 'Credit_Limit',
 'Total_Revolving_Bal',
 'Avg_Open_To_Buy',
 'Total_Amt_Chng_Q4_Q1',
 'Total_Trans_Amt',
 'Total_Trans_Ct',
 'Total_Ct_Chng_Q4_Q1',
 'Avg_Utilization_Ratio']

In [57]:
X_test_array = np.array([[43, 0, 2, 5, 1, 2, 1, 36, 6, 3, 2, 2570, 2107, 463, 0.651, 4058, 83, 0.766, 0.82]])
X_test_array

array([[4.300e+01, 0.000e+00, 2.000e+00, 5.000e+00, 1.000e+00, 2.000e+00,
        1.000e+00, 3.600e+01, 6.000e+00, 3.000e+00, 2.000e+00, 2.570e+03,
        2.107e+03, 4.630e+02, 6.510e-01, 4.058e+03, 8.300e+01, 7.660e-01,
        8.200e-01]])

In [58]:
X_test_scaled = pd.DataFrame(data=X_test_array, columns=df_column_names)

In [59]:
X_test_scaled

Customer_Age  Gender  Dependent_count  Education_Level  Marital_Status  \
0          43.0     0.0              2.0              5.0             1.0   

   Income_Category  Card_Category  Months_on_book  Total_Relationship_Count  \
0              2.0            1.0            36.0                       6.0   

   Months_Inactive_12_mon  Contacts_Count_12_mon  Credit_Limit  \
0                     3.0                    2.0        2570.0   

   Total_Revolving_Bal  Avg_Open_To_Buy  Total_Amt_Chng_Q4_Q1  \
0               2107.0            463.0                 0.651   

   Total_Trans_Amt  Total_Trans_Ct  Total_Ct_Chng_Q4_Q1  Avg_Utilization_Ratio  
0           4058.0            83.0                0.766                   0.82

In [60]:
X_scaler = load(open('../04 Pre-processing Template/X_scaler.pkl', 'rb'))

In [61]:
#List columns that need scaling
col_names = ['Months_on_book', 'Total_Relationship_Count', 'Months_Inactive_12_mon',
       'Contacts_Count_12_mon', 'Credit_Limit', 'Total_Revolving_Bal',
       'Avg_Open_To_Buy', 'Total_Amt_Chng_Q4_Q1', 'Total_Trans_Amt',
       'Total_Trans_Ct', 'Total_Ct_Chng_Q4_Q1']
col_names

['Months_on_book',
 'Total_Relationship_Count',
 'Months_Inactive_12_mon',
 'Contacts_Count_12_mon',
 'Credit_Limit',
 'Total_Revolving_Bal',
 'Avg_Open_To_Buy',
 'Total_Amt_Chng_Q4_Q1',
 'Total_Trans_Amt',
 'Total_Trans_Ct',
 'Total_Ct_Chng_Q4_Q1']

In [62]:
#Create dataframe of just the columns to be scaled
X_test_features = X_test_scaled[col_names]
X_test_features.head()

Months_on_book  Total_Relationship_Count  Months_Inactive_12_mon  \
0            36.0                       6.0                     3.0   

   Contacts_Count_12_mon  Credit_Limit  Total_Revolving_Bal  Avg_Open_To_Buy  \
0                    2.0        2570.0               2107.0            463.0   

   Total_Amt_Chng_Q4_Q1  Total_Trans_Amt  Total_Trans_Ct  Total_Ct_Chng_Q4_Q1  
0                 0.651           4058.0            83.0                0.766

In [63]:
#Transform the data
X_test_features = X_scaler.transform(X_test_features.values)
X_test_features

array([[0.53488372, 1.        , 0.5       , 0.33333333, 0.03421338,
        0.83710767, 0.01332831, 0.19163968, 0.20291679, 0.56589147,
        0.20624663]])

In [64]:
#Updated originally copied df with new scaled features
X_test_scaled[col_names] = X_test_features

In [65]:
X_test_scaled

Customer_Age  Gender  Dependent_count  Education_Level  Marital_Status  \
0          43.0     0.0              2.0              5.0             1.0   

   Income_Category  Card_Category  Months_on_book  Total_Relationship_Count  \
0              2.0            1.0        0.534884                       1.0   

   Months_Inactive_12_mon  Contacts_Count_12_mon  Credit_Limit  \
0                     0.5               0.333333      0.034213   

   Total_Revolving_Bal  Avg_Open_To_Buy  Total_Amt_Chng_Q4_Q1  \
0             0.837108         0.013328               0.19164   

   Total_Trans_Amt  Total_Trans_Ct  Total_Ct_Chng_Q4_Q1  Avg_Utilization_Ratio  
0         0.202917        0.565891             0.206247                   0.82

In [66]:
#Import ML model
randomforest = joblib.load("randomforest_model_trained.sav")

In [67]:
#Import ML Model using pickle
randomforest = pickle.load(open("randomforest_model_trained.sav", 'rb'))

In [68]:
#Check that it works
predictions_forest = randomforest.predict(X_test_scaled)

In [69]:
predictions_forest

array([[0., 1.]], dtype=float32)

In [70]:
#Predictions - 0 is Attrited, 1 is Existing Customer
predictions_forest_decoded = np.argmax(predictions_forest, axis=1)
predictions_forest_decoded

array([1])

In [71]:
print(predictions_forest_decoded)

[1]


In [74]:
predictions_forest_decoded[0]

1

In [75]:
if (predictions_forest_decoded[0] == 0):
    print(f"Customer is at risk of churn")
elif (predictions_forest_decoded[0] == 1):
    print(f"Customer is not at risk of churn")

Customer is not at risk of churn
